export const users = [
  {
    id: '12312411412',
    name: 'Ernesto Che Guevara',
    avatar: 'https://historytime.ru/wp-content/uploads/2016/10/che-770x578.jpg',
    timeLastMessage: '20200214',
    lastMessage: 'How do I know when my form is validating before submit?',
    isOnline: false,
  }, {
    id: '2141241241',
    name: 'Marine DeMerlin',
    avatar: 'https://img5.goodfon.ru/wallpaper/nbig/e/5e/evgenii-bulatov-devushka-litso-vzgliad-ruki-kamni-portret.jpg',
    timeLastMessage: '20200212',
    lastMessage: 'How do I determine if my submission handler is executing?',
    isOnline: true,
  }, {
    id: '1212412412',
    name: 'Bob Marley',
    avatar: 'https://avatars.yandex.net/get-music-content/113160/9ad61744.p.1402/200x200',
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: false,
  }, {
    id: '31242134412',
    name: 'Bob Char',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: true,
  }, {
    id: '312434234412',
    name: 'Mila Romanove',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: true,
  }, {
    id: '31241241412',
    name: 'Ched Mincher',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: true,
  }, {
    id: '3124142342',
    name: 'Abraam Lincoln',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: false,
  }, {
    id: '3124123412',
    name: 'Dima Weget',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: true,
  }, {
    id: '234232412412',
    name: 'Noris Man',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: false,
  }, {
    id: '31241242342',
    name: 'Chad Boldin',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: true,
  }, {
    id: '31241242412',
    name: 'Kris Black',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: true,
  }, {
    id: '312412414234',
    name: 'Lion Cenedi',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: false,
  }, {
    id: '31241243432',
    name: 'Ehli Norton',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: true,
  }, {
    id: '23423423454',
    name: 'Gustov Cheferson',
    avatar: null,
    timeLastMessage: '20200213',
    lastMessage: 'To submit a form in Formik, you need to somehow fire off the provided',
    isOnline: true,
  }
]
